# Generated by Django 4.2.3 on 2023-07-12 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'empleados_staff',
            },
        ),
        migrations.CreateModel(
            name='Moviment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrada', models.CharField(max_length=50)),
                ('fecha_salida', models.CharField(max_length=50)),
                ('hora_entrada', models.CharField(max_length=50)),
                ('hora_salida', models.CharField(max_length=50)),
                ('sentido', models.CharField(max_length=50, null='ENTRADA')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.staff')),
            ],
            options={
                'db_table': 'empleados_moviments',
            },
        ),
        migrations.CreateModel(
            name='Autorization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.CharField(max_length=50)),
                ('hora_final', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=50)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.staff')),
            ],
            options={
                'db_table': 'empleados_autorization',
            },
        ),
    ]
